version: "1.0.0"
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    image: staffys_delivery_client
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
      - ./next.config.js:/app/next.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
    env_file:
      - ./.env
    container_name: staffys_delivery_client_local
    ports:
      - 3000:3000
    tty: true
    entrypoint: ["npm", "run", "dev"]
    networks:
      - staffys_api_network
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: staffys_delivery_client
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
      - /app/coverage
      - ./next.config.js:/app/next.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
    container_name: staffys_delivery_client_local_test
    ports:
      - 3000:3000
    tty: true
    entrypoint: ["npm", "run", "test:watch"]
    networks:
      - staffys_api_network
networks:
  staffys_api_network:
    external: true
