export const deliveryPackages = [
  {
    id: 1,
    destination: "Calle 1",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 2,
    destination: "Calle 2",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 3,
    destination: "Calle 3",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 4,
    destination: "Calle 4",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 5,
    destination: "Calle 5",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 6,
    destination: "Calle 6",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
];
