export const deliveryPackages = [
  {
    id: 13,
    destination: "Calle 1",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 14,
    destination: "Calle 2",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 15,
    destination: "Calle 3",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 16,
    destination: "Calle 4",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 17,
    destination: "Calle 5",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
  {
    id: 18,
    destination: "Calle 6",
    addressee: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: false,
  },
];
